# Generated by Django 5.2.7 on 2025-10-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-fecha_inicio', '-destacado'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['evento', 'categoria'], 'verbose_name': 'Categoría del Evento', 'verbose_name_plural': 'Categorías de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Comentario de Evento', 'verbose_name_plural': 'Comentarios de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registrado_en'], 'verbose_name': 'Registro de Evento', 'verbose_name_plural': 'Registros de Eventos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad máxima'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lugar',
            field=models.CharField(max_length=300, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='events.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='comentario',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registrado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado en'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['fecha_inicio', 'activo'], name='events_even_fecha_i_5df566_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['destacado', 'activo'], name='events_even_destaca_91c209_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcomment',
            index=models.Index(fields=['evento', '-creado_en'], name='events_even_evento__872cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['evento', 'usuario'], name='events_even_evento__5553e5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registrado_en'], name='events_even_registr_fa4e36_idx'),
        ),
    ]
