# Generated by Django 5.2.7 on 2025-10-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tipo',
            field=models.CharField(choices=[('CHARLA', 'Charla'), ('TALLER', 'Taller'), ('FERIA', 'Feria'), ('CONCIERTO', 'Concierto')], default='CHARLA', max_length=20, verbose_name='Tipo de evento'),
        ),
    ]
